---
- hosts: 172.31.31.240
  become: yes
  tasks:
  - name: I want to display the hostname
    command: hostname
    register: myresult
  - name: i Want to display first tasks
    debug:
       msg: "{{myresult}}"
  - name: install git
    apt:
     name: git
     state: present
    when: myresult.stderr ==""
  - name: install tree
    apt:
     name: tree
     state: present
    when: myresult.stderr !=""