---
- hosts: 172.31.31.240
  become: yes
  tasks:
  - include_tasks: file.yml 
  - nmae: install webserver
    apt:
     name: apache2
     state: present

  - name: restart the server
    service:
     name: apache2
     state: restarted
     
