---
- hosts: appservers
  become: yes
  tasks:
  - name: install httpd server
    apt: 
      name: httpd
      state: present
  - name: copy index.html
    copy:
      src: index.html
      dest: /var/www/html/index.html
  - name: service httpd start
    service:
      name: httpd
      state: started
