---
- hosts: appservers
  become: yes
  tasks:
  - name: install nginx server
    apt: 
      name: nginx
      state: present
  - name: service nginx start
    service:
      name: nginx
      state: started
