- hosts: mywebservers
  become: yes
  tasks:
  - name: i Want to install apache2 on ubuntu servers
    apt:
      name: "{{mywebpackageforubuntu}}"
      state: present
    when: ansible_os_family=="Debian"
  - name: I want git install httpd on ubuntu server
    apt:
      name: "{{mywebpackageforubuntu}}"
      state: present
    when: ansible_os_family=="Debian"
